"""add_show_in_navbar_to_blogcategory

Revision ID: 72427f5c39fe
Revises: dfddd140d0b9
Create Date: 2026-06-22 15:19:36.778827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72427f5c39fe'
down_revision: Union[str, Sequence[str], None] = 'dfddd140d0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogcategory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_in_navbar', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogcategory', schema=None) as batch_op:
        batch_op.drop_column('show_in_navbar')

    # ### end Alembic commands ###
