"""add_analytics_tables

Revision ID: a931b3877521
Revises: b02b00d48142
Create Date: 2026-06-21 12:34:51.012224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a931b3877521'
down_revision: Union[str, Sequence[str], None] = 'b02b00d48142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_country_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'country_code', name='uq_zone_country_date_code')
    )
    with op.batch_alter_table('zone_country_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_country_analytics_date'), ['date'], unique=False)

    op.create_table('zone_daily_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zone_daily_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_daily_analytics_date'), ['date'], unique=True)

    op.create_table('zone_device_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'device_type', name='uq_zone_device_date_type')
    )
    with op.batch_alter_table('zone_device_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_device_analytics_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_device_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_device_analytics_date'))

    op.drop_table('zone_device_analytics')
    with op.batch_alter_table('zone_daily_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_daily_analytics_date'))

    op.drop_table('zone_daily_analytics')
    with op.batch_alter_table('zone_country_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_country_analytics_date'))

    op.drop_table('zone_country_analytics')
    # ### end Alembic commands ###
