"""add short_description to blogcategory

Revision ID: af2d947e0cb0
Revises: 72427f5c39fe
Create Date: 2026-06-22 16:00:39.209479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af2d947e0cb0'
down_revision: Union[str, Sequence[str], None] = '72427f5c39fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogcategory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('short_description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('short_description_zh', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogcategory', schema=None) as batch_op:
        batch_op.drop_column('short_description_zh')
        batch_op.drop_column('short_description_en')
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###
