"""remove_requests_and_rename_to_count

Revision ID: b0ad52ec1fd0
Revises: a931b3877521
Create Date: 2026-06-21 15:42:38.900466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b0ad52ec1fd0'
down_revision: Union[str, Sequence[str], None] = 'a931b3877521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone_daily_analytics', 'requests')
    op.alter_column('zone_country_analytics', 'requests', new_column_name='count')
    op.alter_column('zone_device_analytics', 'requests', new_column_name='count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zone_device_analytics', 'count', new_column_name='requests')
    op.alter_column('zone_country_analytics', 'count', new_column_name='requests')
    op.add_column('zone_daily_analytics', sa.Column('requests', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###
