"""add position to blogcategory

Revision ID: dfddd140d0b9
Revises: b0ad52ec1fd0
Create Date: 2026-06-22 12:39:02.409003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dfddd140d0b9'
down_revision: Union[str, Sequence[str], None] = 'b0ad52ec1fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogcategory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogcategory', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
