"""create blog category table

Revision ID: fb35b97b5d56
Revises: cadd372dbf94
Create Date: 2026-06-19 11:43:57.097377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb35b97b5d56'
down_revision: Union[str, Sequence[str], None] = 'cadd372dbf94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogcategory',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name_zh', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blogcategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blogcategory_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_blogcategory_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogcategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogcategory_slug'))
        batch_op.drop_index(batch_op.f('ix_blogcategory_name'))

    op.drop_table('blogcategory')
    # ### end Alembic commands ###
